version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - add_ssh_keys:
          fingerprints:
            - "7b:7d:43:df:65:13:7f:55:79:4d:75:9a:4d:bc:cd:87"
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker container
          command: docker build -t jhrv/testapp:latest .
      - run:
          name: Login to Dockerhub
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - run:
          name: Release new version
          command: |
            version=$(($(git describe --abbrev=0 --tags)+1))
            git tag -a "${version}" -m "${version}"
            git push --tags
            docker tag jhrv/testapp:latest jhrv/testapp:${version}
            docker push jhrv/testapp:latest
            docker push jhrv/testapp:${version}
#
