version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker container
          command: docker build -t jhrv/testapp:latest .
      - run:
          name: Login to Dockerhub
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - run:
          name: Release new version
          command: |
            version=$(date "+%Y-%m-%d")-$(git --no-pager log -1 --pretty=%h)
            docker tag jhrv/testapp:latest jhrv/testapp:${version}
            docker push jhrv/testapp:latest
            docker push jhrv/testapp:${version}
#
