apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    prometheus.io/path: isAlive
    prometheus.io/scrape: "true"
  labels:
    app: testapp
  name: testapp
  namespace: default
spec:
  rules:
  - host: testapp.nais.oera-q.local
    http:
      paths:
      - backend:
          serviceName: testapp
          servicePort: 80
        path: /
