name: build and push
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build + push
      run: |
          version=$(date "+%Y-%m-%d")-$(git --no-pager log -1 --pretty=%h)
          ghcr_image_prefix=ghcr.io/nais/testapp
          docker image build -t ${ghcr_image_prefix}:latest -t ${ghcr_image_prefix}:${version} .
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
          docker image push ${ghcr_image_prefix}:latest
          docker image push ${ghcr_image_prefix}:${version}
