  name: go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@master
      path: ${{ go.module-path }}
      
    - name: Build
      working-directory: ${{ go.module-path }}
      run: docker build -t docker.pkg.github.com/nais/testapp/testapp:latest .
   
