name: go
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@master      
    - name: Build
      run: docker build -t docker.pkg.github.com/nais/testapp/testapp:latest .
   
