name: build and push
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - uses: actions/checkout@master      
    - name: build + push
      run: |
          version=$(date "+%Y-%m-%d")-$(git --no-pager log -1 --pretty=%h)
          image_prefix=docker.pkg.github.com/nais/testapp/testapp
          docker build -t ${image_prefix}:latest -t ${image_prefix}:${version} .
          echo ${{ secrets.GITHUB_PASSWORD }} | docker login docker.pkg.github.com --username ${{ secrets.GITHUB_USERNAME }} --password-stdin
          docker push ${image_prefix}:latest
          docker push ${image_prefix}:${version}
